DECLARE
    vcount INTEGER := 0;
BEGIN
    SELECT
        COUNT(1)
    INTO vcount
    FROM
        dba_users
    WHERE
        username = 'PANDA';

    IF vcount != 0 THEN
        EXECUTE IMMEDIATE ( 'DROP USER panda CASCADE' );
    END IF;
END;
/

CREATE USER panda IDENTIFIED BY panda;

GRANT dba TO panda;

--GRANT EXECUTE ON DBMS_SESSION TO panda;

GRANT ALL PRIVILEGES TO panda;

GRANT SELECT ON v$sgainfo TO panda;

GRANT SELECT ON v$sga TO panda;

GRANT SELECT ON v$pgastat TO panda;

GRANT SELECT ON v$session TO panda;

GRANT SELECT ON v$process TO panda;

GRANT SELECT ON v$spparameter TO panda;

GRANT SELECT ON v$database TO panda;

GRANT SELECT ON v$instance TO panda;

GRANT SELECT ON v$datafile TO panda;

GRANT SELECT ON v$controlfile TO panda;

GRANT SELECT ON v$tablespace TO panda;

GRANT SELECT ON dba_tablespaces TO panda;

GRANT SELECT ON dba_tablespaces TO panda;

GRANT SELECT ON dba_users TO panda;

--conn panda/panda@//localhost:1521/orclpdb

ALTER SESSION SET current_schema = panda;

-- CREATE TABLES

CREATE TABLE account (
    avatar CLOB,
    username VARCHAR2(100) NOT NULL,
    fullname NVARCHAR2(100) NOT NULL,
    CONSTRAINT pk_account PRIMARY KEY ( username )
);

CREATE TABLE project (
    id          NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
    username    VARCHAR2(100) NOT NULL,
    name        NVARCHAR2(100),
    description CLOB,
    priority    NUMBER,
    created_at  TIMESTAMP,
    updated_at  TIMESTAMP,
    started_at  TIMESTAMP,
    ended_at    TIMESTAMP,
    CONSTRAINT pk_project PRIMARY KEY ( id ),
    CONSTRAINT fk_project_account FOREIGN KEY ( username )
        REFERENCES account ( username )
);

CREATE TABLE task (
    id                NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
    pid               NUMBER,
    description       CLOB NOT NULL,
    done              NUMBER(1, 0) DEFAULT 0,
    type_date         NUMBER,
    is_full_day       NUMBER(1, 0) DEFAULT 0,
    type_loop         NUMBER,
    done_after_n_days NUMBER,
    priority          NUMBER,
    created_at        TIMESTAMP,
    updated_at        TIMESTAMP,
    started_at        TIMESTAMP,
    ended_at          TIMESTAMP,
    CONSTRAINT pk_task PRIMARY KEY ( id ),
    CONSTRAINT fk_task_project FOREIGN KEY ( pid )
        REFERENCES project ( id )
);

CREATE TABLE collection (
    id       NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR2(100) NOT NULL,
    name     NVARCHAR2(100),
    CONSTRAINT pk_collection PRIMARY KEY ( id ),
    CONSTRAINT fk_collect_card_account FOREIGN KEY ( username )
        REFERENCES account ( username )
);

CREATE TABLE card (
    id                 NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
    memory             NUMBER,
    n_learn            NUMBER,
    n_missed           NUMBER,
    learn_next_time_at TIMESTAMP,
    CONSTRAINT pk_card PRIMARY KEY ( id )
);

CREATE TABLE flashcard (
    cid   NUMBER,
    front NVARCHAR2(255),
    back  NVARCHAR2(255),
    CONSTRAINT pk_flashcard PRIMARY KEY ( cid ),
    CONSTRAINT fk_flashcard_card FOREIGN KEY ( cid )
        REFERENCES card ( id )
);

CREATE TABLE vocab (
    word  NVARCHAR2(100) NOT NULL,
    audio CLOB,
    ipa   NVARCHAR2(50),
    CONSTRAINT pk_vocab PRIMARY KEY ( word )
);

CREATE TABLE vocab_typevocab (
    word           NVARCHAR2(100),
    pos            NVARCHAR2(10),
    cid            NUMBER,
    meaning        NVARCHAR2(100) NOT NULL,
    n_write        NUMBER,
    n_write_missed NUMBER,
    CONSTRAINT pk_vocab_typevocab PRIMARY KEY ( word,
                                                pos ),
    CONSTRAINT fk_vocab_typevocab_vocab FOREIGN KEY ( word )
        REFERENCES vocab ( word ),
    CONSTRAINT fk_vocab_typevocab_card FOREIGN KEY ( cid )
        REFERENCES card ( id )
);

--CREATE TABLE example (
--    id       NUMBER
--        GENERATED BY DEFAULT AS IDENTITY,
--    sentence NVARCHAR2(100),
--    type     NUMBER,
--    CONSTRAINT pk_example PRIMARY KEY ( id )
--);
--
--CREATE TABLE example_vocab_typevocab (
--    sid  NUMBER,
--    word NVARCHAR2(100),
--    pos  NVARCHAR2(10),
--    CONSTRAINT pk_svt PRIMARY KEY ( sid,
--                                    word,
--                                    pos ),
--    CONSTRAINT fk_svt_example FOREIGN KEY ( sid )
--        REFERENCES example ( id ),
--    CONSTRAINT fk_svt_vocab_typevocab FOREIGN KEY ( word,
--                                                    pos )
--        REFERENCES vocab_typevocab ( word,
--                                     pos )
--);

CREATE TABLE sentence (
    id         NUMBER
        GENERATED BY DEFAULT AS IDENTITY,
    origin     NVARCHAR2(100),
    translated NVARCHAR2(100),
    type       NUMBER(3),
    CONSTRAINT pk_sentence PRIMARY KEY ( id )
);

CREATE TABLE sentence_vocab_typevocab (
    sid  NUMBER,
    word NVARCHAR2(100),
    pos  NVARCHAR2(10),
    CONSTRAINT pk_svt2 PRIMARY KEY ( sid,
                                     word,
                                     pos ),
    CONSTRAINT fk_svt_sentence2 FOREIGN KEY ( sid )
        REFERENCES sentence ( id ),
    CONSTRAINT fk_svt_vocab_typevocab2 FOREIGN KEY ( word,pos )
        REFERENCES vocab_typevocab ( word,pos )
);

CREATE TABLE collection_card (
    collect_id NUMBER,
    card_id    NUMBER,
    CONSTRAINT pk_collect_card PRIMARY KEY ( collect_id,
                                             card_id ),
    CONSTRAINT fk_collect_card_collect FOREIGN KEY ( collect_id )
        REFERENCES collection ( id ),
    CONSTRAINT fk_collect_card_card FOREIGN KEY ( card_id )
        REFERENCES card ( id )
);

-- PROCEDURE

CREATE OR REPLACE PROCEDURE addaccount (
    p_username VARCHAR2,
    p_fullname NVARCHAR2,
    p_password VARCHAR2
) AS
    v_sql VARCHAR2(4000);
    v_project_id NUMBER;
    v_task_id NUMBER;
    up_username VARCHAR2(255);
BEGIN
    up_username := UPPER(p_username);
    v_sql := 'CREATE USER '
             || p_username
             || ' IDENTIFIED BY '
             || p_password;
    EXECUTE IMMEDIATE v_sql;
    v_sql := 'GRANT CREATE SESSION, CONNECT TO ' || p_username;    
    EXECUTE IMMEDIATE v_sql;
    
    INSERT INTO ACCOUNT (avatar, username, fullname)
    VALUES (null, up_username, p_fullname);
    BEGIN
        INSERT INTO project (username, name, description, priority, created_at, updated_at)
        VALUES (up_username, 'Inboxes', null, 0, SYSTIMESTAMP, SYSTIMESTAMP)
        RETURNING id INTO v_project_id;
        
        BEGIN
            INSERT INTO task (pid, description, done, type_date, is_full_day, type_loop, done_after_n_days, priority, created_at, updated_at)
            VALUES (v_project_id, 'Inbox created automacally', 0, null, null, 0, 0, 0, SYSTIMESTAMP, SYSTIMESTAMP)
            RETURNING id INTO v_task_id;
        END;
    END;
    
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END addaccount;
/

CREATE OR REPLACE PROCEDURE signout (
    p_username VARCHAR2
) AS
BEGIN
    FOR session_rec IN (
        SELECT
            sid,
            serial#
        FROM
            v$session
        WHERE
            username = p_username
            and
            sid != sys_context('USERENV', 'SID')
    ) LOOP
        EXECUTE IMMEDIATE 'ALTER SYSTEM KILL SESSION '''
                          || session_rec.sid
                          || ','
                          || session_rec.serial#
                          || ''' IMMEDIATE';
    END LOOP;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END signout;
/

--- PROCEDURE CARD

CREATE OR REPLACE PROCEDURE selectcardsanalysismemory (
    p_cards_cursor OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_cards_cursor FOR SELECT
                                                                                memory,
                                                                                COUNT(*) AS count
                                                                            FROM
                                                                                card
                                                                                LEFT JOIN collection_card cc ON cc.card_id = card.id
                                                                                LEFT JOIN collection      c ON c.id = cc.collect_id
                                                    WHERE
                                                        c.username = sys_context('USERENV', 'CURRENT_USER')
                            GROUP BY
                                memory
                            ORDER BY
                                memory ASC;

END;
/

CREATE OR REPLACE PROCEDURE getcardsanalysismemory (
    p_cursor OUT SYS_REFCURSOR
) IS
BEGIN
    OPEN p_cursor FOR SELECT
                                                              memory,
                                                              COUNT(*) AS count
                                                          FROM
                                                              card
                                                              LEFT JOIN collection_card cc ON cc.card_id = card.id
                                                              LEFT JOIN collection      c ON c.id = cc.collect_id
                                        WHERE
                                            c.username = sys_context('USERENV', 'CURRENT_USER')
                      GROUP BY
                          memory
                      ORDER BY
                          memory ASC;

END;
/


-- END PROCEDURE CARD

--- PROCEDURE VOCAB

-- c? 
--CREATE OR REPLACE PROCEDURE AddVocab (
--    p_word IN NVARCHAR2,
--    p_pos IN NVARCHAR2,
--    p_meaning IN NVARCHAR2,
--    p_audio IN CLOB,
--    p_ipa IN NVARCHAR2
--)
--AS
--    v_id NUMBER;
--BEGIN
--savepoint start_trans;
--    INSERT INTO Card (memory, n_learn, n_missed, learn_next_time_at)
--    VALUES (0, 0, 0, SYSDATE);
--
--    v_id := NULL; 
--
--    SELECT SEQ_VOCAB_TYPEVOCAB.CURRVAL INTO v_id FROM DUAL;
--
--    INSERT INTO Vocab_TypeVocab (word, pos, cid, meaning, n_write, n_write_missed)
--    VALUES (p_word, p_pos, v_id, p_meaning, 0, 0);
--
--    INSERT INTO Vocab (word, audio, ipa)
--    VALUES (p_word, p_audio, p_ipa);
--EXCEPTION
--    WHEN OTHERS THEN
--        ROLLBACK TO start_trans;
--        RAISE;
--END;
--/
-- m?i, thï¿½m sequence 
CREATE SEQUENCE seq_vocab_typevocab;
/

CREATE OR REPLACE PROCEDURE addvocab (
    p_word    IN NVARCHAR2,
    p_pos     IN NVARCHAR2,
    p_meaning IN NVARCHAR2,
    p_audio   IN CLOB,
    p_ipa     IN NVARCHAR2
) AS
    l_id INT;
BEGIN
    INSERT INTO card (
        memory,
        n_learn,
        n_missed,
        learn_next_time_at
    ) VALUES (
        0,
        0,
        0,
        sysdate
    );

    SELECT
        seq_vocab_typevocab.NEXTVAL
    INTO l_id
    FROM
        dual;

    INSERT INTO vocab_typevocab (
        word,
        pos,
        cid,
        meaning,
        n_write,
        n_write_missed
    ) VALUES (
        p_word,
        p_pos,
        l_id,
        p_meaning,
        0,
        0
    );

    INSERT INTO vocab (
        word,
        audio,
        ipa
    ) VALUES (
        p_word,
        p_audio,
        p_ipa
    );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END addvocab;
/

CREATE OR REPLACE FUNCTION select_vocab RETURN SYS_REFCURSOR
IS
    list_vocab SYS_REFCURSOR;
BEGIN
-- open cursor
    OPEN list_vocab FOR SELECT
                                *
                            FROM
                                VOCAB_TYPEVOCAB v
                                INNER JOIN CARD c
                                ON v.cid = c.id
                                INNER JOIN COLLECTION_CARD CC
                                ON CC.CARD_ID = c.id
                                INNER JOIN COLLECTION COL
                                ON CC.COLLECT_ID = COL.ID
                                WHERE COL.username = 'panda_user'
                                ;
  -- Return the cursor

    RETURN list_vocab;
END;
/

-- END PROCEDURE VOCAB

--- PROCEDURE SENTENCE

CREATE OR REPLACE PROCEDURE addsentence (
    origin     IN NVARCHAR2,
    translated IN NVARCHAR2,
    type       IN NUMBER,
    word       IN NVARCHAR2,
    pos        IN NVARCHAR2
) AS
    sid INT;
BEGIN
    INSERT INTO sentence (
        origin,
        translated,
        type
    ) VALUES (
        origin,
        translated,
        type
    ) RETURNING id INTO sid;

    INSERT INTO sentence_vocab_typevocab (
        sid,
        word,
        pos
    ) VALUES (
        sid,
        word,
        pos
    );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END addsentence;
/

-- END PROCEDURE SENTENCE

--- PROCEDURE COLLECTION

CREATE OR REPLACE PROCEDURE selectcollections (
    p_username IN VARCHAR2,
    p_cursor   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR SELECT
                                            *
                                        FROM
                                            collection
                      WHERE
                          username = p_username;

END selectcollections;
/

CREATE OR REPLACE PROCEDURE selectcollectionsanalysis (
    p_username IN VARCHAR2,
    p_cursor   OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR SELECT
                                                              c.id,
                                                              c.name,
                                                              COUNT(cc.card_id)  AS total_card,
                                                              SUM(card.n_learn)  AS n_learn,
                                                              SUM(card.n_missed) AS n_missed,
                                                              COUNT(
                                                                  CASE
                                                                      WHEN card.memory > 5 THEN
                                                                          1
                                                                      ELSE
                                                                          NULL
                                                                  END
                                                              )                  AS memory
                                                          FROM
                                                              collection      c
                                                              LEFT JOIN collection_card cc ON cc.collect_id = c.id
                                                              LEFT JOIN card            card ON card.id = cc.card_id
                                        WHERE
                                            username = p_username
                      GROUP BY
                          c.name,
                          c.id;

END selectcollectionsanalysis;
/

CREATE OR REPLACE PROCEDURE deletecollection (
    name_param IN NVARCHAR2
) AS
BEGIN
    DELETE FROM collection
    WHERE
            name = name_param
        AND username = user;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE addcollection (
    name_param IN NVARCHAR2
) AS
BEGIN
    INSERT INTO collection (
        username,
        name
    ) VALUES (
        user,
        name_param
    );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
END;
/

-- END PROCEDURE COLLECTION

--- PROCEDURE PROJECT

CREATE OR REPLACE PROCEDURE select_projects (
    p_cursor OUT SYS_REFCURSOR
) AS
    curr_username VARCHAR2(30); -- Adjust the size based on your needs
BEGIN
    -- Assign the current user to the variable
    SELECT USER INTO curr_username FROM DUAL;

    -- Open the cursor using the declared variable
    OPEN p_cursor FOR
        SELECT
            ID, NAME, DESCRIPTION, PRIORITY, CREATED_AT, UPDATED_AT, STARTED_AT, ENDED_AT
        FROM
            panda.project
        WHERE
            username = curr_username;
END select_projects;
/


--CREATE OR REPLACE PROCEDURE select_projects (
--    p_cursor OUT SYS_REFCURSOR
--) AS
--BEGIN
--    BEGIN
--        OPEN p_cursor FOR
--            SELECT ID, NAME, DESCRIPTION, PRIORITY, CREATED_AT, UPDATED_AT, STARTED_AT, ENDED_AT
--            FROM project
--            WHERE username = sys_context('USERENV', 'CURRENT_USER');
--    EXCEPTION
--        WHEN OTHERS THEN
--            IF p_cursor%ISOPEN THEN
--                CLOSE p_cursor;
--            END IF;
--            RAISE;
--    END;
--END select_projects;
--/


-- END PROCEDURE PROJECT

--- PROCEDURE TASK

CREATE OR REPLACE PROCEDURE selectinboxes (
    p_cursor OUT SYS_REFCURSOR
) AS
    p_username VARCHAR2(100);
BEGIN
    p_username := sys_context('USERENV', 'CURRENT_USER');
    OPEN p_cursor FOR SELECT
                                            t.*
                                        FROM
                                            task    t
                                            RIGHT JOIN project p ON p.id = t.pid
                      WHERE
                              p.username = p_username
                          AND p.name = 'Inbox';

END selectinboxes;
/

CREATE OR REPLACE PROCEDURE selecttaskstoday (
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR SELECT
                                            t.*
                                        FROM
                                            task    t
                                            RIGHT JOIN project p ON p.id = t.pid
                      WHERE
                              p.username = sys_context('USERENV', 'CURRENT_USER')
                          AND p.ended_at <= sysdate
                          AND p.started_at >= trunc(sysdate);

END selecttaskstoday;
/

CREATE OR REPLACE PROCEDURE selecttaskstodaybyprojectid (
    p_pid    IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR SELECT
                                            t.*
                                        FROM
                                            task    t
                                            RIGHT JOIN project p ON p.id = t.pid
                      WHERE
                              p.username = sys_context('USERENV', 'CURRENT_USER')
                          AND p.ended_at <= sysdate
                          AND p.started_at >= trunc(sysdate)
                          AND t.pid = p_pid;

END selecttaskstodaybyprojectid;
/

CREATE OR REPLACE PROCEDURE inserttask (
    p_pid               IN NUMBER,
    p_description       IN NCLOB,
    p_done              IN NUMBER,
    p_type_date         IN NUMBER,
    p_is_full_day       IN NUMBER,
    p_type_loop         IN NUMBER,
    p_done_after_n_days IN NUMBER,
    p_priority          IN NUMBER,
    p_created_at        IN DATE,
    p_updated_at        IN DATE,
    p_started_at        IN DATE,
    p_ended_at          IN DATE
) AS
BEGIN
    INSERT INTO task (
        pid,
        description,
        done,
        type_date,
        is_full_day,
        type_loop,
        done_after_n_days,
        priority,
        created_at,
        updated_at,
        started_at,
        ended_at
    ) VALUES (
        p_pid,
        p_description,
        p_done,
        p_type_date,
        p_is_full_day,
        p_type_loop,
        p_done_after_n_days,
        p_priority,
        p_created_at,
        p_updated_at,
        p_started_at,
        p_ended_at
    );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE insertinbox (
    p_description IN NCLOB
) AS
    v_pid INT;
BEGIN
    SELECT
        id
    INTO v_pid
    FROM
        project
    WHERE
        project.username = sys_context('USERENV', 'CURRENT_USER');

    INSERT INTO task (
        pid,
        description
    ) VALUES (
        v_pid,
        p_description
    );

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

CREATE OR REPLACE PROCEDURE deletetask AS
    v_tid INT;
BEGIN
    SELECT
        t.id
    INTO v_tid
    FROM
        task    t
        LEFT JOIN project p ON p.id = t.pid
    WHERE
        p.username = sys_context('USERENV', 'CURRENT_USER');

    DELETE FROM task
    WHERE
        task.id = v_tid;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        ROLLBACK;
        RAISE;
END;
/

-- END PROCEDURE TASK


DROP ROLE PANDA_USER_ROLE;

CREATE ROLE PANDA_USER_ROLE;
GRANT CONNECT TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.ADDCOLLECTION TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.ADDSENTENCE TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.ADDVOCAB TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.DELETECOLLECTION TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.DELETETASK TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.GETCARDSANALYSISMEMORY TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.INSERTINBOX TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.INSERTTASK TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.SELECTCARDSANALYSISMEMORY TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.SELECTCOLLECTIONS TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.SELECTCOLLECTIONSANALYSIS TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.SELECTINBOXES TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.SELECT_PROJECTS TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.SELECTTASKSTODAY TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.SELECTTASKSTODAYBYPROJECTID TO PANDA_USER_ROLE;
GRANT EXECUTE ON PANDA.SIGNOUT TO PANDA_USER_ROLE;



DECLARE
    vcount INTEGER := 0;
BEGIN
    SELECT
        COUNT(1)
    INTO vcount
    FROM
        dba_users
    WHERE
        username = 'PANDA_REGISTER';

    IF vcount != 0 THEN
        EXECUTE IMMEDIATE ( 'DROP USER PANDA_REGISTER CASCADE' );
    END IF;
END;
/

CREATE USER panda_register IDENTIFIED BY panda_register;

GRANT connect TO panda_register;

GRANT EXECUTE ON panda.addaccount TO panda_register;

DECLARE
    vcount INTEGER := 0;
BEGIN
    SELECT
        COUNT(1)
    INTO vcount
    FROM
        dba_users
    WHERE
        username = 'PANDA_USER';

    IF vcount != 0 THEN
        EXECUTE IMMEDIATE ( 'DROP USER PANDA_USER CASCADE' );
    END IF;
END;
/

--CREATE USER panda_user IDENTIFIED BY panda_user;
call addaccount('panda_user', 'PANDA USER', 'panda_user');
/

GRANT PANDA_USER_ROLE TO panda_user;
GRANT PANDA_USER_ROLE TO panda;
GRANT SELECT ON PROJECT TO panda;

Alter session set current_schema=panda;
--DECLARE
--    v_clob CLOB;
--    v_blob BLOB;
--    v_bfile BFILE;
--BEGIN
--    v_bfile := BFILENAME('C:\Users\Khoa\Pictures', 'meme-meo-cuoi.jpg');
--
--    DBMS_LOB.fileopen(v_bfile, DBMS_LOB.file_readonly);
--
--    DBMS_LOB.loadfromfile(v_blob, v_bfile, DBMS_LOB.getlength(v_bfile));
--
--    DBMS_LOB.createtemporary(v_clob, TRUE);
--    DBMS_LOB.converttoclob(dest_lob => v_clob,
--                            src_blob => v_blob,
--                            amount => DBMS_LOB.getLength(v_blob),
--                            dest_offset => 1,
--                            src_offset => 1,
--                            bfile_csid => DBMS_LOB.default_csid,
--                            lang_context => DBMS_LOB.default_lang_ctx,
--                            warning => DBMS_LOB.warnings);
--
--    INSERT INTO account (avatar, username, fullname) VALUES (v_clob, 'panda_user', 'PANDA USER');
--
--    DBMS_LOB.fileclose(v_bfile);
--    DBMS_LOB.freetemporary(v_clob);
--END;
--/


--INSERT INTO ACCOUNT (AVATAR, USERNAME, FULLNAME) VALUES ('panda_user', 'PANDA USER');


INSERT INTO project (username, name, description, priority, created_at, updated_at, started_at, ended_at)
VALUES ('PANDA_USER', 'oracle', NULL, 1, TO_DATE('20/12/2023', 'DD/MM/YYYY'), TO_DATE('05/01/2024', 'DD/MM/YYYY'), TO_DATE('20/01/2024', 'DD/MM/YYYY'), TO_DATE('01/06/2024', 'DD/MM/YYYY'));

INSERT INTO task (pid, description, priority, created_at)
VALUES (2, 'Write unit tests', 2, TO_DATE('2024-03-05', 'YYYY-MM-DD'));

INSERT INTO task (pid, description, priority, created_at)
VALUES (2, 'Fix bugs', 3, TO_DATE('2024-03-05', 'YYYY-MM-DD'));

INSERT INTO task (pid, description, priority, created_at)
VALUES (2, 'Deploy to production', 1, TO_DATE('2024-03-05', 'YYYY-MM-DD'));

INSERT INTO collection (username, name) VALUES
('PANDA_USER', 'Oracle');

INSERT INTO card (memory, n_learn, n_missed, learn_next_time_at)
VALUES
(0, 0, 0, null);

INSERT INTO card (memory, n_learn, n_missed, learn_next_time_at)
VALUES
(0, 0, 0, null);

INSERT INTO card (memory, n_learn, n_missed, learn_next_time_at)
VALUES
(0, 0, 0, null);

INSERT INTO card (memory, n_learn, n_missed, learn_next_time_at)
VALUES
(0, 0, 0, null);

INSERT INTO flashcard (cid, front, back) VALUES (1, 'Oracle database là gì?', 'Oracle database là m?t h? qu?n tr? c? s? d? li?u quan h? (RDBMS) ???c phát tri?n b?i Oracle Corporation. Nó ???c s? d?ng r?ng rãi trong các doanh nghi?p và t? ch?c ?? l?u tr? và qu?n lý d? li?u.');
INSERT INTO flashcard (cid, front, back) VALUES (2, 'Các phiên b?n oracle', 'Enterprise edition, standard edition, express edition, oracle lite');
INSERT INTO flashcard (cid, front, back) VALUES (3, 'Express edition dùng cho h? ?i?u hành nào?', 'Linux và windows');
INSERT INTO flashcard (cid, front, back) VALUES (4, 'Machine learning có t? phiên b?n nào c?a oracle?', '18c');


INSERT INTO collection_card (collect_id, card_id) VALUES (1, 1);
INSERT INTO collection_card (collect_id, card_id) VALUES (1, 2);
INSERT INTO collection_card (collect_id, card_id) VALUES (1, 3);
INSERT INTO collection_card (collect_id, card_id) VALUES (1, 4);

-- 2
INSERT INTO collection (username, name) values
('PANDA_USER', 'English');


INSERT INTO card (memory, n_learn, n_missed, learn_next_time_at)
VALUES
(0, 0, 0, null);
/
INSERT INTO collection_card (collect_id, card_id) VALUES (2, 5);


INSERT INTO vocab(word, audio, ipa)
values
    ('healthfully', null, '/?hel?.f?l.i/');

INSERT INTO vocab_typevocab(word, pos, cid, meaning, n_write, n_write_missed)
values
    ('healthfully', 'adverb', 5, 'in a way that helps you to produce good health', 0, 0);
    
INSERT INTO sentence(origin, translated, type) VALUES ('The website gives advice to dieters for ways to eat more healthfully and lose weight.', null, 0);
INSERT INTO sentence(origin, translated, type) VALUES ('Living healthfully requires being active and getting regular exercise.', null, 0);
/
INSERT INTO SENTENCE_VOCAB_TYPEVOCAB (sid, word, pos) VALUES (1, 'healthfully', 'adverb');
INSERT INTO SENTENCE_VOCAB_TYPEVOCAB (sid, word, pos) VALUES (2, 'healthfully', 'adverb');
/
--INSERT INTO ACCOUNT VALUES ('panda', '123');
/
--INSERT INTO PANDA.PROJECT (username, name, description, created_at, updated_at, started_at, ended_at) 
--VALUES ('panda', 'panda', '', null, null, null, null);
/