/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panda.user;

import model.Sentence;

/**
 *
 * @author Khoa
 */
public class CpnExampleVocab extends javax.swing.JPanel {

    /**
     * Creates new form CpnSampleVocab
     */
    private boolean isDeleted;
    private Sentence example;

    public Sentence getExample() {
        example.setOrigin(txtFieldOrigin.getText());
        example.setTranslated(txtFieldTranslated.getText());
        return example;
    }

    public CpnExampleVocab() {
        initComponents();
        isDeleted = false;
        example = new Sentence();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDeleteSentence = new javax.swing.JButton();
        pnSentence = new javax.swing.JPanel();
        txtFieldTranslated = new javax.swing.JTextField();
        txtFieldOrigin = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(476, 76));

        btnDeleteSentence.setText("Delete");
        btnDeleteSentence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteSentenceMouseClicked(evt);
            }
        });

        txtFieldTranslated.setToolTipText("Translated sample language");

        txtFieldOrigin.setToolTipText("Origin sample language");
        txtFieldOrigin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldOriginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnSentenceLayout = new javax.swing.GroupLayout(pnSentence);
        pnSentence.setLayout(pnSentenceLayout);
        pnSentenceLayout.setHorizontalGroup(
            pnSentenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSentenceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnSentenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldTranslated, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                    .addComponent(txtFieldOrigin))
                .addContainerGap())
        );
        pnSentenceLayout.setVerticalGroup(
            pnSentenceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSentenceLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(txtFieldOrigin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFieldTranslated, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnSentence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDeleteSentence)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnSentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteSentence, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteSentenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteSentenceMouseClicked
        // TODO add your handling code here:
        isDeleted = true;
        setVisible(false);
        if (getParent() != null) {
            getParent().remove(this);
            revalidate();
            repaint();
        }
    }//GEN-LAST:event_btnDeleteSentenceMouseClicked

    private void txtFieldOriginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldOriginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldOriginActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteSentence;
    private javax.swing.JPanel pnSentence;
    private javax.swing.JTextField txtFieldOrigin;
    private javax.swing.JTextField txtFieldTranslated;
    // End of variables declaration//GEN-END:variables
}
