/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panda.user;

import dao.DBConnectionDAO;
import dao.SystemDAO;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Account;
import model.DBConnection;
import panda.user.entities.ManageCollection;
import panda.user.entities.ManageFlashcard;
import panda.user.entities.ManageProject;
import panda.user.entities.ManageSentence;
import panda.user.entities.ManageTask;
import panda.user.entities.ManageVocab;
import panda.user.system.AddDatafile;
import panda.user.system.CreateTablespace;
import panda.user.system.User;
import panda.user.system.mgnAudit;
import panda.user.system.mgnAudit;
import panda.user.system.mgnProfile;
import panda.user.system.mgnRole;
/**
 *
 * @author nguye
 */
public class CpnProfile extends javax.swing.JPanel {

    String sid;
    String serial;
    String addr;
    /**
     * Creates new form CpnProfile
     */
    String[] systems = {
        "SGA", "PGA", "PROCESS", "INSTANCE", "DATABASE", "DATAFILE", "CONTROL FILES", "SPFILE",
        "SESSION", "TABLESPACES", "DATAFILES", "POLICIES", "AUDIT", "USERS", "PROFILES"
    };
    String system = "SGA";
    boolean isDialog = false;
    public CpnProfile() {
        initComponents();
        listSystems.setListData(systems);
        if (!"panda_user".equals(DBConnection.getUsername())) {
            LoadDataTableModel(SystemDAO.LoadSGA());
        }
    }

    public void reloadTable() {
        if (listSystems.getSelectedIndex() != -1) {
            system = systems[listSystems.getSelectedIndex()];
        }
        switch (system) {
            case "PGA":
                LoadDataTableModel(SystemDAO.LoadPGA());
                break;
            case "PROCESS":
                LoadDataTableModel(SystemDAO.LoadProcessInfo());
                break;
            case "INSTANCE":
                LoadDataTableModel(SystemDAO.LoadInstanceInfo());
                break;
            case "DATABASE":
                LoadDataTableModel(SystemDAO.LoadDatabaseInfo());
                break;
            case "DATAFILE":
                LoadDataTableModel(SystemDAO.LoadDataFileInfo());
                break;
            case "CONTROL FILES":
                LoadDataTableModel(SystemDAO.LoadControlFile());
                break;
            case "SPFILE":
                LoadDataTableModel(SystemDAO.LoadSpFileInfo());
                break;
            case "SESSION":
                LoadDataTableModel(SystemDAO.LoadSession());
                break;
            case "TABLESPACES":
                LoadDataTableModel(SystemDAO.LoadTableSpace());
                break;
            case "DATAFILES":
                LoadDataTableModel(SystemDAO.LoadDataFileInfo());//LoadDataFiles());
                break;
            case "POLICIES":
                LoadDataTableModel(SystemDAO.LoadPolicy());
                break;
            case "AUDIT":
                LoadDataTableModel(SystemDAO.LoadAudit());
                break;
            case "USERS":
                LoadDataTableModel(SystemDAO.LoadUsers());
                break;
            case "PROFILES":
                LoadDataTableModel(SystemDAO.loadProfiles());
                break;
            default:
                LoadDataTableModel(SystemDAO.LoadSGA());
                break;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        txtFieldEmail = new javax.swing.JTextField();
        txtFieldFullname = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        txtFieldPassword = new javax.swing.JTextField();
        txtFieldConfirmPassword = new javax.swing.JTextField();
        btnSignout = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnCollection = new javax.swing.JButton();
        btnSentence = new javax.swing.JButton();
        btnFlashcard = new javax.swing.JButton();
        btnProject = new javax.swing.JButton();
        btnTask = new javax.swing.JButton();
        btnVocab = new javax.swing.JButton();
        btnPolicy = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();
        btnAudit = new javax.swing.JButton();
        btnRole = new javax.swing.JButton();
        btnUser = new javax.swing.JButton();
        btnTestRole = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCreateTableSpace = new javax.swing.JButton();
        btnKillSession = new javax.swing.JButton();
        btnViewSession = new javax.swing.JButton();
        btnAddDatafile = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSystem = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSystems = new javax.swing.JList<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        txtFieldEmail.setText("Email");

        txtFieldFullname.setText("Fullname");

        jButton7.setText("Update");

        txtFieldPassword.setText("Password");

        txtFieldConfirmPassword.setText("Confirm password");

        btnSignout.setText("SignOut");
        btnSignout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSignoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFieldPassword)
                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFieldFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtFieldConfirmPassword))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSignout, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignout))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Management"));

        btnCollection.setText("Collection");
        btnCollection.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCollectionMouseClicked(evt);
            }
        });

        btnSentence.setText("Sentence");
        btnSentence.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSentenceMouseClicked(evt);
            }
        });

        btnFlashcard.setText("Flashcard");
        btnFlashcard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnFlashcardMouseClicked(evt);
            }
        });

        btnProject.setText("Project");
        btnProject.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnProjectMouseClicked(evt);
            }
        });

        btnTask.setText("Task");
        btnTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTaskMouseClicked(evt);
            }
        });

        btnVocab.setText("Vocab");
        btnVocab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVocabMouseClicked(evt);
            }
        });

        btnPolicy.setText("Policy");
        btnPolicy.setEnabled(false);

        btnProfile.setText("Profile");
        btnProfile.setEnabled(false);

        btnAudit.setText("Audit");
        btnAudit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAuditMouseClicked(evt);
            }
        });

        btnRole.setText("Role");
        btnRole.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRoleMouseClicked(evt);
            }
        });

        btnUser.setText("User");
        btnUser.setEnabled(false);
        btnUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUserMouseClicked(evt);
            }
        });

        btnTestRole.setText("Test Role");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnCollection)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnVocab)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnFlashcard)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btnSentence)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnProject)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 15, Short.MAX_VALUE)
                        .addComponent(btnTask))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnPolicy)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnProfile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAudit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTestRole)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRole)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCollection)
                    .addComponent(btnSentence)
                    .addComponent(btnFlashcard)
                    .addComponent(btnProject)
                    .addComponent(btnTask)
                    .addComponent(btnVocab))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPolicy)
                    .addComponent(btnProfile)
                    .addComponent(btnAudit)
                    .addComponent(btnRole)
                    .addComponent(btnUser)
                    .addComponent(btnTestRole))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCreateTableSpace.setText("Tạo tablespace");
        btnCreateTableSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateTableSpaceMouseClicked(evt);
            }
        });

        btnKillSession.setText("Kill Session");
        btnKillSession.setEnabled(false);
        btnKillSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKillSessionMouseClicked(evt);
            }
        });

        btnViewSession.setText("Xem Session");
        btnViewSession.setEnabled(false);
        btnViewSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewSessionMouseClicked(evt);
            }
        });

        btnAddDatafile.setText("Thêm datafile");
        btnAddDatafile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddDatafileMouseClicked(evt);
            }
        });

        btnRemove.setText("Xóa");
        btnRemove.setEnabled(false);
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateTableSpace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAddDatafile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemove)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKillSession)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateTableSpace)
                    .addComponent(btnKillSession)
                    .addComponent(btnViewSession)
                    .addComponent(btnAddDatafile)
                    .addComponent(btnRemove))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableSystem.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableSystem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableSystem.setMinimumSize(new java.awt.Dimension(200, 0));
        jTableSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSystemMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTableSystemMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTableSystem);

        listSystems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listSystemsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listSystems);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 182, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listSystemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSystemsMouseClicked
        // TODO add your handling code here:
        reloadTable();
        String sys_name = systems[listSystems.getSelectedIndex()];
        if (sys_name != "SESSION") {
            btnViewSession.setEnabled(false);
            btnKillSession.setEnabled(false);
        }else if(sys_name != "TABLESPACES" || sys_name != "DATAFILES"){
            btnRemove.setEnabled(false);
        }
    }//GEN-LAST:event_listSystemsMouseClicked

    private void jTableSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSystemMouseClicked
        // TODO add your handling code here:
        int row = jTableSystem.getSelectedRow();
        if(row == -1) return;
        String sys_name = systems[listSystems.getSelectedIndex()];
        if (sys_name == "SESSION") {
            sid = jTableSystem.getValueAt(row, 0).toString();
            serial = jTableSystem.getValueAt(row, 2).toString();
            addr = jTableSystem.getValueAt(row, 0).toString();
                btnViewSession.setEnabled(true);
                btnKillSession.setEnabled(true);
        }else if(sys_name == "TABLESPACES" || sys_name == "DATAFILES"){
            btnRemove.setEnabled(true);
        }
        //sid, serial#
    }//GEN-LAST:event_jTableSystemMouseClicked

    private void btnKillSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKillSessionMouseClicked
        // TODO add your handling code here:
        if (systems[listSystems.getSelectedIndex()] == "SESSION") {
            int row = jTableSystem.getSelectedRow();
            if (row != -1) {
                sid = jTableSystem.getValueAt(row, 0).toString();
                serial = jTableSystem.getValueAt(row, 1).toString();
                if (SystemDAO.killSession(sid, serial)) {
                    LoadDataTableModel(SystemDAO.LoadSession());
                }
            }
        }
    }//GEN-LAST:event_btnKillSessionMouseClicked

    private void btnViewSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewSessionMouseClicked
        // TODO add your handling code here:
        if (systems[listSystems.getSelectedIndex()] == "SESSION") {
            //int row = jTableSystem.getSelectedRow();
            if (!sid.isEmpty()) {

                ViewSession vsession = new ViewSession(sid.toString());
                vsession.setVisible(true);
                vsession.setLocationRelativeTo(null);
            }
        }
    }//GEN-LAST:event_btnViewSessionMouseClicked

    private void btnCreateTableSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateTableSpaceMouseClicked
        // TODO add your handling code here:
        CreateTablespace createTablespace = new CreateTablespace();
        createTablespace.setVisible(true);
        createTablespace.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCreateTableSpaceMouseClicked

    private void btnCollectionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCollectionMouseClicked
        // TODO add your handling code here:
        ManageCollection collection = new ManageCollection();
        collection.setVisible(true);
        collection.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCollectionMouseClicked

    private void btnProjectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnProjectMouseClicked
        // TODO add your handling code here:
        ManageProject project = new ManageProject();
        project.setVisible(true);
        project.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnProjectMouseClicked

    private void btnVocabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVocabMouseClicked
        // TODO add your handling code here:
        ManageVocab vocab = new ManageVocab();
        vocab.setVisible(true);
        vocab.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnVocabMouseClicked

    private void btnFlashcardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnFlashcardMouseClicked
        // TODO add your handling code here:
        ManageFlashcard flashcard = new ManageFlashcard();
        flashcard.setVisible(true);
        flashcard.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnFlashcardMouseClicked

    private void btnSentenceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSentenceMouseClicked
        // TODO add your handling code here:
        ManageSentence sentence = new ManageSentence();
        sentence.setVisible(true);
        sentence.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnSentenceMouseClicked

    private void btnTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTaskMouseClicked
        // TODO add your handling code here:
        ManageTask task = new ManageTask();
        task.setVisible(true);
        task.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnTaskMouseClicked

    private void btnAddDatafileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddDatafileMouseClicked
        // TODO add your handling code here:
        AddDatafile datafile = new AddDatafile();
        datafile.setVisible(true);
        datafile.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAddDatafileMouseClicked

    private void btnRemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseClicked
        // TODO add your handling code here:
        String sys = system;
        String object = jTableSystem.getValueAt(jTableSystem.getSelectedRow(), 0).toString();
        try{
            switch(sys){
                case "TABLESPACES":
                    SystemDAO.deleteTablespace(object);
                    break;
                case "DATAFILES":
                    SystemDAO.deleteDatafile(object);
                    break;
            }
            JOptionPane.showConfirmDialog(this, "Successfully!", "Thông báo!", JOptionPane.DEFAULT_OPTION);
        }catch(Exception e){
            JOptionPane.showConfirmDialog(this, e.getMessage(), "Thông báo!", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_btnRemoveMouseClicked

    private void btnSignoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSignoutMouseClicked
        // TODO add your handling code here:
        if (DBConnection.getConn() != null) {
            Object[] values = {
                DBConnection.getUsername().toUpperCase()
            };
            try {
                DBConnectionDAO.CallProcedureNoParameter("signout", values);
            } catch (Exception ex) {
                ex.printStackTrace();
            }
            DBConnection.closeConnection();
        }
//        try {
//            Account.deleteSessionDevice();
//        } catch (IOException ex) {
//            Logger.getLogger(CpnProfile.class.getName()).log(Level.SEVERE, null, ex);
//        }
        
    }//GEN-LAST:event_btnSignoutMouseClicked

    private void btnRoleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRoleMouseClicked
        // TODO add your handling code here:
        mgnRole.main(systems);
    }//GEN-LAST:event_btnRoleMouseClicked

    private void jTableSystemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSystemMousePressed
        // TODO add your handling code here:
        int selectedRow = jTableSystem.getSelectedRow();
        if(evt.getClickCount() == 2
                && selectedRow != -1)
        {
            switch(system){
                case "USERS":
                    String username = jTableSystem.getValueAt(selectedRow, 1).toString();
                    User user = new User(username);
                    user.setVisible(true);
                    user.setLocationRelativeTo(null);
                    break;
                case "PROFILES":
                    mgnProfile.main(systems);
                    break;
                default:
                    break;
            }
        }
    }//GEN-LAST:event_jTableSystemMousePressed

    private void btnUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUserMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnUserMouseClicked

    private void btnAuditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAuditMouseClicked
        // TODO add your handling code here:
        mgnAudit.main(systems);
    }//GEN-LAST:event_btnAuditMouseClicked

//    public void LoadSGA() {
//        DefaultTableModel sga = SystemDAO.LoadSGA();
//        jTableSystem.setModel(sga);
//    }
    private void LoadDataTableModel(DefaultTableModel model) {
        try{
            if (model.getColumnCount() < 15) {
                jTableSystem.setAutoResizeMode(JTable.AUTO_RESIZE_SUBSEQUENT_COLUMNS);
            } else {
                jTableSystem.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
            }
            jTableSystem.setModel(model);
        }catch(Exception e){
            
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDatafile;
    private javax.swing.JButton btnAudit;
    private javax.swing.JButton btnCollection;
    private javax.swing.JButton btnCreateTableSpace;
    private javax.swing.JButton btnFlashcard;
    private javax.swing.JButton btnKillSession;
    private javax.swing.JButton btnPolicy;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnProject;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnRole;
    private javax.swing.JButton btnSentence;
    private javax.swing.JButton btnSignout;
    private javax.swing.JButton btnTask;
    private javax.swing.JButton btnTestRole;
    private javax.swing.JButton btnUser;
    private javax.swing.JButton btnViewSession;
    private javax.swing.JButton btnVocab;
    private javax.swing.JButton jButton7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableSystem;
    private javax.swing.JList<String> listSystems;
    private javax.swing.JTextField txtFieldConfirmPassword;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldFullname;
    private javax.swing.JTextField txtFieldPassword;
    // End of variables declaration//GEN-END:variables
}
