/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package panda.user;

import dao.SystemDAO;
import java.util.HashMap;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import panda.user.system.CreateTablespace;

/**
 *
 * @author nguye
 */
public class CpnProfile extends javax.swing.JPanel {

    /**
     * Creates new form CpnProfile
     */
    String[] systems = {
        "SGA", "PGA", "PROCESS", "INSTANCE", "DATABASE", "DATAFILE", "CONTROL FILES", "SPFILE",
        "SESSION", "TABLESPACE"
    };

    public CpnProfile() {
        initComponents();
        listSystems.setListData(systems);
        LoadDataTableModel(SystemDAO.LoadSGA());

    }
    
    public void reloadTable(){
        String system = "SGA";
        if(listSystems.getSelectedIndex() != -1){
            system = systems[listSystems.getSelectedIndex()];
        }
        switch (system) {
            case "PGA":
                LoadDataTableModel(SystemDAO.LoadPGA());
                break;
            case "PROCESS":
                LoadDataTableModel(SystemDAO.LoadProcessInfo());
                break;
            case "INSTANCE":
                LoadDataTableModel(SystemDAO.LoadInstanceInfo());
                break;
            case "DATABASE":
                LoadDataTableModel(SystemDAO.LoadDatabaseInfo());
                break;
            case "DATAFILE":
                LoadDataTableModel(SystemDAO.LoadDataFileInfo());
                break;
            case "CONTROL FILES":
                LoadDataTableModel(SystemDAO.LoadControlFile());
                break;
            case "SPFILE":
                LoadDataTableModel(SystemDAO.LoadSpFileInfo());
                break;
            case "SESSION":
                LoadDataTableModel(SystemDAO.LoadSession());
                break;
            case "TABLESPACE":
                LoadDataTableModel(SystemDAO.LoadTableSpace());
                break;
            default:
                LoadDataTableModel(SystemDAO.LoadSGA());
                break;
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        txtFieldEmail = new javax.swing.JTextField();
        txtFieldFullname = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        txtFieldPassword = new javax.swing.JTextField();
        txtFieldConfirmPassword = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnCreateTableSpace = new javax.swing.JButton();
        btnKillSession = new javax.swing.JButton();
        btnViewSession = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableSystem = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSystems = new javax.swing.JList<>();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        txtFieldEmail.setText("Email");

        txtFieldFullname.setText("Fullname");

        jButton7.setText("Update");

        txtFieldPassword.setText("Password");

        txtFieldConfirmPassword.setText("Confirm password");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtFieldPassword)
                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtFieldFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(txtFieldConfirmPassword))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButton7)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldFullname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Management"));

        jButton1.setText("Collection");

        jButton2.setText("Vocabulary");

        jButton3.setText("Flashcard");

        jButton4.setText("Project");

        jButton5.setText("Task");

        jButton6.setText("Vocab");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        btnCreateTableSpace.setText("Tạo tablespace");
        btnCreateTableSpace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCreateTableSpaceMouseClicked(evt);
            }
        });

        btnKillSession.setText("Kill Session");
        btnKillSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKillSessionMouseClicked(evt);
            }
        });

        btnViewSession.setText("Xem Session");
        btnViewSession.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnViewSessionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnCreateTableSpace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnViewSession)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKillSession)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCreateTableSpace)
                    .addComponent(btnKillSession)
                    .addComponent(btnViewSession))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTableSystem.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTableSystem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableSystem.setMinimumSize(new java.awt.Dimension(200, 0));
        jTableSystem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableSystemMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableSystem);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        listSystems.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listSystemsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listSystems);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listSystemsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listSystemsMouseClicked
        // TODO add your handling code here:
        reloadTable();

    }//GEN-LAST:event_listSystemsMouseClicked

    private void jTableSystemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableSystemMouseClicked
        // TODO add your handling code here:

        //sid, serial#
    }//GEN-LAST:event_jTableSystemMouseClicked

    private void btnKillSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKillSessionMouseClicked
        // TODO add your handling code here:
        if (systems[listSystems.getSelectedIndex()] == "SESSION") {
            int row = jTableSystem.getSelectedRow();
            if (row != -1) {
                Object sid = jTableSystem.getValueAt(row, 1);
                Object serial = jTableSystem.getValueAt(row, 2);
                if (SystemDAO.killSession(sid, serial)) {
                    LoadDataTableModel(SystemDAO.LoadSession());
                }
            }
        }
    }//GEN-LAST:event_btnKillSessionMouseClicked

    private void btnViewSessionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnViewSessionMouseClicked
        // TODO add your handling code here:
        if (systems[listSystems.getSelectedIndex()] == "SESSION") {
            int row = jTableSystem.getSelectedRow();
            if (row != -1) {
                Object sid = jTableSystem.getValueAt(row, 1);
                Object serial = jTableSystem.getValueAt(row, 2);
                Object addr = jTableSystem.getValueAt(row, 0);
                ViewSession vsession = new ViewSession(sid.toString());
                vsession.setVisible(true);
                vsession.setLocationRelativeTo(null);
            }
        }
    }//GEN-LAST:event_btnViewSessionMouseClicked

    private void btnCreateTableSpaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCreateTableSpaceMouseClicked
        // TODO add your handling code here:
        CreateTablespace createTablespace = new CreateTablespace();
        createTablespace.setVisible(true);
        createTablespace.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnCreateTableSpaceMouseClicked

//    public void LoadSGA() {
//        DefaultTableModel sga = SystemDAO.LoadSGA();
//        jTableSystem.setModel(sga);
//    }
    private void LoadDataTableModel(DefaultTableModel model) {
        jTableSystem.setModel(model);
    }

//    public void LoadDataModel(String system) {
//        jTableSystem.setModel(SystemDAO.loadInfoSystem(system));
//    }

//    public void LoadPGA() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }
//
//    public void LoadProcess() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }
//
//    public void LoadInstance() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }
//
//    public void LoadDatabase() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }
//
//    public void LoadDatafile() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }
//
//    public void LoadControlFiles() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }
//
//    public void LoadSpfile() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }
//
//    public void LoadSession() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }
//
//    public void LoadTablespace() {
//        DefaultTableModel pga = SystemDAO.loadInfoSystem();
//        jTableSystem.setModel(pga);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateTableSpace;
    private javax.swing.JButton btnKillSession;
    private javax.swing.JButton btnViewSession;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableSystem;
    private javax.swing.JList<String> listSystems;
    private javax.swing.JTextField txtFieldConfirmPassword;
    private javax.swing.JTextField txtFieldEmail;
    private javax.swing.JTextField txtFieldFullname;
    private javax.swing.JTextField txtFieldPassword;
    // End of variables declaration//GEN-END:variables
}
